[package]
name = "hashindex-rs"
version = "0.2.0"
edition = "2024"
license-file = "COPYING"

[dependencies]
argh = "0.1.13"
async-task = "4.7.1"
futures = "0.3.31"
num_cpus = "1.17.0"
smol = {version = "2"}
tempfile = "3.20.0"
xxhash-rust = {version = "0.8.12", features = ["xxh3", "xxh64"]}
